import type { Metadata } from "next";
import { Inter, Inter_Tight, Work_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import UserProvider from "@/components/user-provider";

const bodyFont = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

// const displayFont = localFont({
//     src: "../../public/ClashDisplay-Variable.woff2",
//     variable: "--font-some-font",
//     display: "swap",
// });

const displayFont = Inter_Tight({
    variable: "--font-some-font",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "message kit",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${bodyFont.className} ${displayFont.variable} antialiased`}
            >
                <UserProvider />
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    // enableSystem
                    disableTransitionOnChange
                >
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
